[package]
name = "encoding-wasm"
version = "0.1.0"
authors = ["Marcos Casagrande <marcoscvp90@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.58"
base64 = "0.12.2"